//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 12/1/2010 7:08:48 AM
namespace SilverlightArchitecture.Repository.SampleData
{
    
    /// <summary>
    /// There are no comments for SampleContainer in the schema.
    /// </summary>
    public partial class DataServiceContainer : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new SampleContainer object.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public DataServiceContainer(global::System.Uri serviceRoot) : 
                base(serviceRoot)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            if (typeName.StartsWith("Sample", global::System.StringComparison.Ordinal))
            {
                return this.GetType().Assembly.GetType(string.Concat("SilverlightArchitecture.Repository.SampleData", typeName.Substring(6)), false);
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("SilverlightArchitecture.Repository.SampleData", global::System.StringComparison.Ordinal))
            {
                return string.Concat("Sample.", clientType.Name);
            }
            return clientType.FullName;
        }
        /// <summary>
        /// There are no comments for BusinessBases in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<BusinessBase> BusinessBases
        {
            get
            {
                if ((this._BusinessBases == null))
                {
                    this._BusinessBases = base.CreateQuery<BusinessBase>("BusinessBases");
                }
                return this._BusinessBases;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<BusinessBase> _BusinessBases;
        /// <summary>
        /// There are no comments for BusinessBases in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToBusinessBases(BusinessBase businessBase)
        {
            base.AddObject("BusinessBases", businessBase);
        }
    }
    /// <summary>
    /// There are no comments for Sample.BusinessBase in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("BusinessBases")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public abstract partial class BusinessBase : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property CreatedBy in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CreatedBy
        {
            get
            {
                return this._CreatedBy;
            }
            set
            {
                this.OnCreatedByChanging(value);
                this._CreatedBy = value;
                this.OnCreatedByChanged();
                this.OnPropertyChanged("CreatedBy");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CreatedBy;
        partial void OnCreatedByChanging(string value);
        partial void OnCreatedByChanged();
        /// <summary>
        /// There are no comments for Property CreatedDate in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime CreatedDate
        {
            get
            {
                return this._CreatedDate;
            }
            set
            {
                this.OnCreatedDateChanging(value);
                this._CreatedDate = value;
                this.OnCreatedDateChanged();
                this.OnPropertyChanged("CreatedDate");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _CreatedDate;
        partial void OnCreatedDateChanging(global::System.DateTime value);
        partial void OnCreatedDateChanged();
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for Sample.Entity in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public abstract partial class Entity : BusinessBase
    {
        /// <summary>
        /// There are no comments for Addresses in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Address> Addresses
        {
            get
            {
                return this._Addresses;
            }
            set
            {
                this._Addresses = value;
                this.OnPropertyChanged("Addresses");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Address> _Addresses = new global::System.Data.Services.Client.DataServiceCollection<Address>(null, System.Data.Services.Client.TrackingMode.None);
    }
    /// <summary>
    /// There are no comments for Sample.Company in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Company : Entity
    {
        /// <summary>
        /// Create a new Company object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="createdBy">Initial value of CreatedBy.</param>
        /// <param name="createdDate">Initial value of CreatedDate.</param>
        /// <param name="companyId">Initial value of CompanyId.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Company CreateCompany(int ID, string createdBy, global::System.DateTime createdDate, int companyId)
        {
            Company company = new Company();
            company.Id = ID;
            company.CreatedBy = createdBy;
            company.CreatedDate = createdDate;
            company.CompanyId = companyId;
            return company;
        }
        /// <summary>
        /// There are no comments for Property CompanyId in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int CompanyId
        {
            get
            {
                return this._CompanyId;
            }
            set
            {
                this.OnCompanyIdChanging(value);
                this._CompanyId = value;
                this.OnCompanyIdChanged();
                this.OnPropertyChanged("CompanyId");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _CompanyId;
        partial void OnCompanyIdChanging(int value);
        partial void OnCompanyIdChanged();
        /// <summary>
        /// There are no comments for Children in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Company> Children
        {
            get
            {
                return this._Children;
            }
            set
            {
                this._Children = value;
                this.OnPropertyChanged("Children");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Company> _Children = new global::System.Data.Services.Client.DataServiceCollection<Company>(null, System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// There are no comments for Parent in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Company Parent
        {
            get
            {
                return this._Parent;
            }
            set
            {
                this._Parent = value;
                this.OnPropertyChanged("Parent");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Company _Parent;
    }
    /// <summary>
    /// There are no comments for Sample.Person in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Person : Entity
    {
        /// <summary>
        /// Create a new Person object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="createdBy">Initial value of CreatedBy.</param>
        /// <param name="createdDate">Initial value of CreatedDate.</param>
        /// <param name="firstName">Initial value of FirstName.</param>
        /// <param name="lastName">Initial value of LastName.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Person CreatePerson(int ID, string createdBy, global::System.DateTime createdDate, string firstName, string lastName)
        {
            Person person = new Person();
            person.Id = ID;
            person.CreatedBy = createdBy;
            person.CreatedDate = createdDate;
            person.FirstName = firstName;
            person.LastName = lastName;
            return person;
        }
        /// <summary>
        /// There are no comments for Property FirstName in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string FirstName
        {
            get
            {
                return this._FirstName;
            }
            set
            {
                this.OnFirstNameChanging(value);
                this._FirstName = value;
                this.OnFirstNameChanged();
                this.OnPropertyChanged("FirstName");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _FirstName;
        partial void OnFirstNameChanging(string value);
        partial void OnFirstNameChanged();
        /// <summary>
        /// There are no comments for Property LastName in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string LastName
        {
            get
            {
                return this._LastName;
            }
            set
            {
                this.OnLastNameChanging(value);
                this._LastName = value;
                this.OnLastNameChanged();
                this.OnPropertyChanged("LastName");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _LastName;
        partial void OnLastNameChanging(string value);
        partial void OnLastNameChanged();
    }
    /// <summary>
    /// There are no comments for Sample.Address in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Address : BusinessBase
    {
        /// <summary>
        /// Create a new Address object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="createdBy">Initial value of CreatedBy.</param>
        /// <param name="createdDate">Initial value of CreatedDate.</param>
        /// <param name="entityId">Initial value of EntityId.</param>
        /// <param name="address1">Initial value of Address1.</param>
        /// <param name="address2">Initial value of Address2.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Address CreateAddress(int ID, string createdBy, global::System.DateTime createdDate, int entityId, string address1, string address2)
        {
            Address address = new Address();
            address.Id = ID;
            address.CreatedBy = createdBy;
            address.CreatedDate = createdDate;
            address.EntityId = entityId;
            address.Address1 = address1;
            address.Address2 = address2;
            return address;
        }
        /// <summary>
        /// There are no comments for Property EntityId in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int EntityId
        {
            get
            {
                return this._EntityId;
            }
            set
            {
                this.OnEntityIdChanging(value);
                this._EntityId = value;
                this.OnEntityIdChanged();
                this.OnPropertyChanged("EntityId");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _EntityId;
        partial void OnEntityIdChanging(int value);
        partial void OnEntityIdChanged();
        /// <summary>
        /// There are no comments for Property Address1 in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Address1
        {
            get
            {
                return this._Address1;
            }
            set
            {
                this.OnAddress1Changing(value);
                this._Address1 = value;
                this.OnAddress1Changed();
                this.OnPropertyChanged("Address1");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Address1;
        partial void OnAddress1Changing(string value);
        partial void OnAddress1Changed();
        /// <summary>
        /// There are no comments for Property Address2 in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Address2
        {
            get
            {
                return this._Address2;
            }
            set
            {
                this.OnAddress2Changing(value);
                this._Address2 = value;
                this.OnAddress2Changed();
                this.OnPropertyChanged("Address2");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Address2;
        partial void OnAddress2Changing(string value);
        partial void OnAddress2Changed();
        /// <summary>
        /// There are no comments for Owner in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Entity Owner
        {
            get
            {
                return this._Owner;
            }
            set
            {
                this._Owner = value;
                this.OnPropertyChanged("Owner");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Entity _Owner;
    }
}
